import 'dart:collection';
import 'dart:convert';
import 'dart:io';

const _generatedMarker =
    '// Generated by tool/prepare_pubdev_module_docs.dart. Do not edit.';
const _yamlGeneratedMarker =
    '# Generated by tool/prepare_pubdev_module_docs.dart. Do not edit.';

class ParameterInfo {
  ParameterInfo(this.type, this.name);

  final String type;
  final String name;
}

class MethodInfo {
  MethodInfo({
    required this.docLines,
    required this.returnType,
    required this.name,
    required this.parameters,
  });

  final List<String> docLines;
  final String returnType;
  final String name;
  final List<ParameterInfo> parameters;
}

class TypedefInfo {
  TypedefInfo({
    required this.docLines,
    required this.name,
    required this.definition,
  });

  final List<String> docLines;
  final String name;
  final String definition;
}

class CallbackTypedefGroup {
  CallbackTypedefGroup({
    required this.callbackType,
    required this.nativeSignatureType,
    required this.dartSignatureType,
    required this.docLines,
  });

  final String callbackType;
  final String nativeSignatureType;
  final String? dartSignatureType;
  final List<String> docLines;
}

class CallbackInteropInfo {
  CallbackInteropInfo({
    required this.helperClassName,
    required this.registrationMethodName,
    required this.registeredCallbackTypeName,
    required this.pointerGetterName,
    required this.userDataGetterName,
  });

  final String helperClassName;
  final String registrationMethodName;
  final String registeredCallbackTypeName;
  final String pointerGetterName;
  final String userDataGetterName;
}

class CallbackReference {
  CallbackReference({
    required this.group,
    required this.usedByMethods,
  });

  final CallbackTypedefGroup group;
  final List<String> usedByMethods;
}

class ModuleInfo {
  ModuleInfo({
    required this.symbolMapVariable,
    required this.getterName,
    required this.libraryName,
    required this.fileName,
    required this.moduleSlug,
    required this.sharedObjects,
    required this.descriptions,
    required this.methods,
    required this.callbackReferences,
    required this.callbackRelatedMissingSymbols,
    required this.unresolvedSymbols,
  });

  final String symbolMapVariable;
  final String getterName;
  final String libraryName;
  final String fileName;
  final String moduleSlug;
  final List<String> sharedObjects;
  final List<String> descriptions;
  final List<MethodInfo> methods;
  final List<CallbackReference> callbackReferences;
  final List<String> callbackRelatedMissingSymbols;
  final List<String> unresolvedSymbols;

  String get descriptionText =>
      descriptions.isEmpty ? 'Unknown module' : descriptions.join(', ');
}

class _Config {
  _Config({
    required this.command,
    required this.version,
    required this.keepGenerated,
  });

  final String command;
  final String version;
  final bool keepGenerated;
}

class _State {
  _State({
    required this.version,
    required this.generatedFiles,
    required this.directoriesToPrune,
    required this.dartdocOptionsBackupPath,
  });

  final String version;
  final List<String> generatedFiles;
  final List<String> directoriesToPrune;
  final String? dartdocOptionsBackupPath;

  Map<String, Object?> toJson() => {
        'version': version,
        'generatedFiles': generatedFiles,
        'directoriesToPrune': directoriesToPrune,
        'dartdocOptionsBackupPath': dartdocOptionsBackupPath,
      };

  static _State fromJson(Map<String, Object?> json) {
    return _State(
      version: json['version']! as String,
      generatedFiles: (json['generatedFiles']! as List<Object?>).cast<String>(),
      directoriesToPrune:
          (json['directoriesToPrune']! as List<Object?>).cast<String>(),
      dartdocOptionsBackupPath: json['dartdocOptionsBackupPath'] as String?,
    );
  }
}

Future<void> main(List<String> args) async {
  final config = _parseArgs(args);
  final rootDir = _repoRoot();

  switch (config.command) {
    case 'prepare':
      await _prepare(rootDir, config);
      return;
    case 'verify':
      await _prepare(rootDir, config);
      final versionId = config.version.replaceAll('.', '_');
      try {
        await _run(
          'dart',
          [
            'doc',
            '--validate-links',
            '-o',
            '.dart_tool/pubdev_module_docs/$versionId/preview',
            '.',
          ],
          workingDirectory: rootDir.path,
        );
        await _runPublishDryRun(workingDirectory: rootDir.path);
      } finally {
        if (!config.keepGenerated) {
          _clean(rootDir, config.version);
        }
      }
      return;
    case 'clean':
      _clean(rootDir, config.version);
      return;
    default:
      throw ArgumentError('Unknown command: ${config.command}');
  }
}

_Config _parseArgs(List<String> args) {
  var command = 'verify';
  var version = '6.0';
  var keepGenerated = false;

  for (var index = 0; index < args.length; index++) {
    final arg = args[index];
    switch (arg) {
      case 'prepare':
      case 'verify':
      case 'clean':
        command = arg;
      case '--version':
        if (index + 1 >= args.length) {
          throw ArgumentError('Missing value for --version');
        }
        version = args[++index];
      case '--keep-generated':
        keepGenerated = true;
      case '-h':
      case '--help':
        stdout.writeln(
          'Usage: dart run tool/prepare_pubdev_module_docs.dart '
          '[prepare|verify|clean] [--version 6.0] [--keep-generated]',
        );
        exit(0);
      default:
        throw ArgumentError('Unknown argument: $arg');
    }
  }

  return _Config(
    command: command,
    version: version,
    keepGenerated: keepGenerated,
  );
}

Directory _repoRoot() {
  final scriptFile = File.fromUri(Platform.script);
  return scriptFile.parent.parent;
}

Future<void> _prepare(Directory rootDir, _Config config) async {
  _clean(rootDir, config.version, allowMissing: true);

  final version = config.version;
  final versionId = version.replaceAll('.', '_');
  final stateDir =
      Directory('${rootDir.path}/.dart_tool/pubdev_module_docs/$versionId')
        ..createSync(recursive: true);
  final stateBackupFile = File('${stateDir.path}/dartdoc_options.yaml.backup');
  if (stateBackupFile.existsSync()) {
    stateBackupFile.deleteSync();
  }

  final generatedBindingsFile = File(
    '${rootDir.path}/lib/src/bindings/$version/generated_bindings.dart',
  );
  final generatedSymbolsFile = File(
    '${rootDir.path}/lib/src/bindings/$version/generated_symbols.dart',
  );
  final tizenLibraryFile = File('${rootDir.path}/lib/$version/tizen.dart');
  final symgenConfigFile = File('${rootDir.path}/configs/$version/symgen.yaml');
  final callbacksLibraryFile = File(
    '${rootDir.path}/packages/tizen_interop_callbacks/lib/'
    'tizen_interop_callbacks.dart',
  );

  for (final file in [
    generatedBindingsFile,
    generatedSymbolsFile,
    tizenLibraryFile,
    symgenConfigFile,
    callbacksLibraryFile,
  ]) {
    if (!file.existsSync()) {
      throw StateError('Missing required file: ${file.path}');
    }
  }

  final methods = _parseMethods(generatedBindingsFile.readAsLinesSync());
  final symbolMaps =
      _parseGeneratedSymbols(generatedSymbolsFile.readAsLinesSync());
  final getters = _parseGetterMap(tizenLibraryFile.readAsStringSync());
  final descriptions =
      _parseSymgenDescriptions(symgenConfigFile.readAsLinesSync());
  final typedefs = _parseTypedefs(generatedBindingsFile.readAsLinesSync());
  final callbackGroups = _buildCallbackTypedefGroups(typedefs);
  final callbackInterop =
      _parseCallbackInteropInfo(callbacksLibraryFile.readAsStringSync());
  final modules = _buildModules(
    version: version,
    versionId: versionId,
    methods: methods,
    symbolMaps: symbolMaps,
    getters: getters,
    descriptions: descriptions,
    callbackGroups: callbackGroups,
  );

  final targetDir = Directory('${rootDir.path}/lib/$version/tizen');
  if (targetDir.existsSync() && targetDir.listSync().isNotEmpty) {
    throw StateError(
      'Refusing to overwrite existing files in ${targetDir.path}. '
      'Run clean first or inspect the directory.',
    );
  }
  targetDir.createSync(recursive: true);

  final categoryName = 'tizen_$versionId';
  final generatedFiles = <String>[];
  final directoriesToPrune = <String>[
    targetDir.path,
    '${rootDir.path}/doc/dartdoc',
    stateDir.path,
  ];
  final dartdocOptionsFile = File('${rootDir.path}/dartdoc_options.yaml');

  try {
    String? backupPath;
    if (dartdocOptionsFile.existsSync()) {
      dartdocOptionsFile.renameSync(stateBackupFile.path);
      backupPath = stateBackupFile.path;
    }

    for (final module in modules) {
      final outputFile = File('${targetDir.path}/${module.fileName}')
        ..writeAsStringSync(
          _buildModuleLibrary(
            version: version,
            categoryName: categoryName,
            module: module,
            callbackInterop: callbackInterop,
          ),
        );
      generatedFiles.add(outputFile.path);
    }

    final landingFile = File('${targetDir.path}/index.dart')
      ..writeAsStringSync(
        _buildLandingLibrary(
          version: version,
          categoryName: categoryName,
          modules: modules,
        ),
      );
    generatedFiles.add(landingFile.path);

    final categoryDocFile = File(
      '${rootDir.path}/doc/dartdoc/tizen_$versionId.md',
    );
    categoryDocFile.parent.createSync(recursive: true);
    categoryDocFile.writeAsStringSync(
      _buildCategoryMarkdown(version: version, modules: modules),
    );
    generatedFiles.add(categoryDocFile.path);

    final footerTextFile = File(
      '${rootDir.path}/doc/dartdoc/tizen_$versionId.footer.txt',
    );
    footerTextFile.writeAsStringSync(
      _buildFooterText(version: version, modules: modules),
    );
    generatedFiles.add(footerTextFile.path);

    dartdocOptionsFile.writeAsStringSync(
      _buildDartdocOptions(
        version: version,
        versionId: versionId,
        categoryName: categoryName,
        modules: modules,
        footerTextPath: 'doc/dartdoc/tizen_$versionId.footer.txt',
      ),
    );
    generatedFiles.add(dartdocOptionsFile.path);

    final state = _State(
      version: version,
      generatedFiles: generatedFiles,
      directoriesToPrune: directoriesToPrune,
      dartdocOptionsBackupPath: backupPath,
    );
    _stateFile(rootDir, version)
      ..parent.createSync(recursive: true)
      ..writeAsStringSync(
        const JsonEncoder.withIndent('  ').convert(state.toJson()),
      );
  } catch (_) {
    for (final path in generatedFiles.reversed) {
      final file = File(path);
      if (file.existsSync()) {
        file.deleteSync();
      }
    }
    if (dartdocOptionsFile.existsSync()) {
      final content = dartdocOptionsFile.readAsStringSync();
      if (content.startsWith(_yamlGeneratedMarker)) {
        dartdocOptionsFile.deleteSync();
      }
    }
    if (stateBackupFile.existsSync()) {
      if (dartdocOptionsFile.existsSync()) {
        dartdocOptionsFile.deleteSync();
      }
      stateBackupFile.renameSync(dartdocOptionsFile.path);
    }
    for (final directoryPath in directoriesToPrune.reversed) {
      _deleteEmptyDirectoryChain(directoryPath, stopAt: rootDir.path);
    }
    rethrow;
  }

  stdout.writeln(
    'Prepared ${modules.length} module libraries for pub.dev under '
    '${targetDir.path}',
  );
}

void _clean(
  Directory rootDir,
  String version, {
  bool allowMissing = false,
}) {
  final stateFile = _stateFile(rootDir, version);
  if (!stateFile.existsSync()) {
    if (!allowMissing) {
      stdout.writeln(
        'No generated pub.dev module docs state found for version $version.',
      );
    }
    return;
  }

  final state = _State.fromJson(
    jsonDecode(stateFile.readAsStringSync()) as Map<String, Object?>,
  );

  for (final path in state.generatedFiles.reversed) {
    final file = File(path);
    if (file.existsSync()) {
      file.deleteSync();
    }
  }

  final dartdocOptionsFile = File('${rootDir.path}/dartdoc_options.yaml');
  if (dartdocOptionsFile.existsSync()) {
    final content = dartdocOptionsFile.readAsStringSync();
    if (content.startsWith(_yamlGeneratedMarker)) {
      dartdocOptionsFile.deleteSync();
    }
  }

  final backupPath = state.dartdocOptionsBackupPath;
  if (backupPath != null) {
    final backupFile = File(backupPath);
    if (backupFile.existsSync()) {
      if (dartdocOptionsFile.existsSync()) {
        dartdocOptionsFile.deleteSync();
      }
      backupFile.renameSync(dartdocOptionsFile.path);
    }
  }

  for (final directoryPath in state.directoriesToPrune.reversed) {
    _deleteEmptyDirectoryChain(directoryPath, stopAt: rootDir.path);
  }

  stateFile.deleteSync();
}

File _stateFile(Directory rootDir, String version) {
  final versionId = version.replaceAll('.', '_');
  return File(
    '${rootDir.path}/.dart_tool/pubdev_module_docs/$versionId/state.json',
  );
}

void _deleteEmptyDirectoryChain(
  String directoryPath, {
  required String stopAt,
}) {
  var current = Directory(directoryPath);
  final stopPath = Directory(stopAt).absolute.path;

  while (current.existsSync() && current.absolute.path.startsWith(stopPath)) {
    if (current.absolute.path == stopPath) {
      return;
    }
    if (current.listSync().isNotEmpty) {
      return;
    }
    final parent = current.parent;
    current.deleteSync();
    current = parent;
  }
}

List<ModuleInfo> _buildModules({
  required String version,
  required String versionId,
  required Map<String, MethodInfo> methods,
  required Map<String, Map<String, List<String>>> symbolMaps,
  required Map<String, String> getters,
  required Map<String, String> descriptions,
  required Map<String, CallbackTypedefGroup> callbackGroups,
}) {
  final modules = <ModuleInfo>[];
  final moduleEntries = symbolMaps.entries.toList()
    ..sort((left, right) {
      final leftGetter = getters[left.key] ?? left.key;
      final rightGetter = getters[right.key] ?? right.key;
      return leftGetter.compareTo(rightGetter);
    });

  for (final entry in moduleEntries) {
    final getterName = getters[entry.key];
    if (getterName == null) {
      stderr.writeln(
          'Skipping ${entry.key}: getter not found in lib/$version/tizen.dart');
      continue;
    }

    final methodMap = LinkedHashMap<String, MethodInfo>();
    final missingSymbols = LinkedHashSet<String>();
    final callbackRelatedMissingSymbols = LinkedHashSet<String>();
    final unresolvedSymbols = LinkedHashSet<String>();
    final callbackUsage = LinkedHashMap<String, LinkedHashSet<String>>();
    final sharedObjects = entry.value.keys.toList(growable: false);

    for (final symbols in entry.value.values) {
      for (final symbol in symbols) {
        final method = methods[symbol];
        if (method == null) {
          if (!missingSymbols.add(symbol)) {
            continue;
          }
          if (_looksLikeCallbackApiSymbol(symbol)) {
            callbackRelatedMissingSymbols.add(symbol);
          } else {
            unresolvedSymbols.add(symbol);
          }
          continue;
        }

        methodMap.putIfAbsent(method.name, () => method);
        for (final callbackType in _extractReferencedCallbackTypes(
          method,
          callbackGroups,
        )) {
          callbackUsage
              .putIfAbsent(callbackType, LinkedHashSet<String>.new)
              .add(method.name);
        }
      }
    }

    final callbackReferences = callbackUsage.entries
        .map(
          (callbackEntry) => CallbackReference(
            group: callbackGroups[callbackEntry.key]!,
            usedByMethods: callbackEntry.value.toList(growable: false),
          ),
        )
        .toList(growable: false);
    final moduleSlug = _moduleSlugFromGetter(getterName);

    modules.add(
      ModuleInfo(
        symbolMapVariable: entry.key,
        getterName: getterName,
        libraryName: 'tizen_${versionId}_${_camelToSnake(getterName)}',
        fileName: '$moduleSlug.dart',
        moduleSlug: moduleSlug,
        sharedObjects: sharedObjects,
        descriptions: sharedObjects
            .map((library) => descriptions[library] ?? library)
            .toSet()
            .toList(growable: false),
        methods: methodMap.values.toList(growable: false),
        callbackReferences: callbackReferences,
        callbackRelatedMissingSymbols:
            callbackRelatedMissingSymbols.toList(growable: false),
        unresolvedSymbols: unresolvedSymbols.toList(growable: false),
      ),
    );
  }

  return modules;
}

Map<String, MethodInfo> _parseMethods(List<String> lines) {
  final methods = <String, MethodInfo>{};
  final docBuffer = <String>[];
  var index = 0;

  while (index < lines.length) {
    final line = lines[index];

    if (line.startsWith('  ///')) {
      docBuffer.add(line.substring(2));
      index++;
      continue;
    }

    final zeroArgumentMethod = RegExp(
      r'^ {2}(?! )(?!late final)(?!Tizen\d+Native)(.+?)\s+(\w+)\(\)\s*\{$',
    ).firstMatch(line);
    if (zeroArgumentMethod != null) {
      final method = MethodInfo(
        docLines: List<String>.from(docBuffer),
        returnType: zeroArgumentMethod.group(1)!.trim(),
        name: zeroArgumentMethod.group(2)!.trim(),
        parameters: const [],
      );
      methods[method.name] = method;
      docBuffer.clear();
      index++;
      continue;
    }

    final multiArgumentMethod = RegExp(
      r'^ {2}(?! )(?!late final)(?!Tizen\d+Native)(.+?)\s+(\w+)\(\s*$',
    ).firstMatch(line);
    if (multiArgumentMethod != null) {
      final parameterLines = <String>[];
      index++;
      while (index < lines.length && lines[index].trim() != ') {') {
        final parameterLine = lines[index].trim();
        if (parameterLine.isNotEmpty) {
          parameterLines.add(parameterLine);
        }
        index++;
      }
      final method = MethodInfo(
        docLines: List<String>.from(docBuffer),
        returnType: multiArgumentMethod.group(1)!.trim(),
        name: multiArgumentMethod.group(2)!.trim(),
        parameters: _parseParameters(parameterLines.join(' ')),
      );
      methods[method.name] = method;
      docBuffer.clear();
      index++;
      continue;
    }

    if (line.trim().isNotEmpty) {
      docBuffer.clear();
    }
    index++;
  }

  return methods;
}

List<ParameterInfo> _parseParameters(String parameterBlock) {
  if (parameterBlock.trim().isEmpty) {
    return const [];
  }
  return _splitParameters(parameterBlock).map(_parseParameter).toList();
}

List<String> _splitParameters(String parameterBlock) {
  final parameters = <String>[];
  final buffer = StringBuffer();
  var angleDepth = 0;
  var parenthesisDepth = 0;
  var squareDepth = 0;

  for (final rune in parameterBlock.runes) {
    final char = String.fromCharCode(rune);
    if (char == '<') {
      angleDepth++;
    } else if (char == '>') {
      if (angleDepth > 0) {
        angleDepth--;
      }
    } else if (char == '(') {
      parenthesisDepth++;
    } else if (char == ')') {
      if (parenthesisDepth > 0) {
        parenthesisDepth--;
      }
    } else if (char == '[') {
      squareDepth++;
    } else if (char == ']') {
      if (squareDepth > 0) {
        squareDepth--;
      }
    } else if (char == ',' &&
        angleDepth == 0 &&
        parenthesisDepth == 0 &&
        squareDepth == 0) {
      final parameter = buffer.toString().trim();
      if (parameter.isNotEmpty) {
        parameters.add(parameter);
      }
      buffer.clear();
      continue;
    }
    buffer.write(char);
  }

  final trailing = buffer.toString().trim();
  if (trailing.isNotEmpty) {
    parameters.add(trailing);
  }

  return parameters;
}

ParameterInfo _parseParameter(String parameter) {
  final separatorIndex = parameter.lastIndexOf(' ');
  if (separatorIndex <= 0 || separatorIndex == parameter.length - 1) {
    throw StateError('Unable to parse parameter: $parameter');
  }
  return ParameterInfo(
    parameter.substring(0, separatorIndex).trim(),
    parameter.substring(separatorIndex + 1).trim(),
  );
}

Map<String, TypedefInfo> _parseTypedefs(List<String> lines) {
  final typedefs = <String, TypedefInfo>{};
  final docBuffer = <String>[];
  var index = 0;

  while (index < lines.length) {
    final line = lines[index];

    if (line.startsWith('///')) {
      docBuffer.add(line);
      index++;
      continue;
    }

    if (line.startsWith('typedef ')) {
      final definitionBuffer = StringBuffer(line.trimRight());
      while (!definitionBuffer.toString().trimRight().endsWith(';')) {
        index++;
        if (index >= lines.length) {
          throw StateError('Unexpected EOF while parsing typedef.');
        }
        definitionBuffer.write('\n${lines[index].trimRight()}');
      }

      final definition = definitionBuffer.toString();
      final nameMatch = RegExp(r'^typedef\s+(\w+)').firstMatch(definition);
      if (nameMatch == null) {
        throw StateError('Unable to determine typedef name: $definition');
      }

      final name = nameMatch.group(1)!;
      typedefs[name] = TypedefInfo(
        docLines: List<String>.from(docBuffer),
        name: name,
        definition: definition,
      );
      docBuffer.clear();
      index++;
      continue;
    }

    if (line.trim().isNotEmpty) {
      docBuffer.clear();
    }
    index++;
  }

  return typedefs;
}

Map<String, CallbackTypedefGroup> _buildCallbackTypedefGroups(
  Map<String, TypedefInfo> typedefs,
) {
  final groups = <String, CallbackTypedefGroup>{};

  for (final entry in typedefs.entries) {
    final callbackType = entry.key;
    if (!callbackType.endsWith('_cb')) {
      continue;
    }

    final nativeSignatureType = '${callbackType}Function';
    final dartSignatureType = 'Dart${callbackType}Function';
    final nativeSignature = typedefs[nativeSignatureType];
    if (nativeSignature == null) {
      continue;
    }

    groups[callbackType] = CallbackTypedefGroup(
      callbackType: callbackType,
      nativeSignatureType: nativeSignatureType,
      dartSignatureType:
          typedefs.containsKey(dartSignatureType) ? dartSignatureType : null,
      docLines: entry.value.docLines,
    );
  }

  return groups;
}

Map<String, Map<String, List<String>>> _parseGeneratedSymbols(
  List<String> lines,
) {
  final symbolMaps = <String, Map<String, List<String>>>{};
  String? currentMap;
  String? currentLibrary;

  for (final rawLine in lines) {
    final line = rawLine.trim();

    final mapMatch = RegExp(
      r'^const\s+Map<String,\s*List<String>>\s+(\w+)\s*=\s*\{$',
    ).firstMatch(line);
    if (mapMatch != null) {
      currentMap = mapMatch.group(1)!;
      symbolMaps[currentMap] = <String, List<String>>{};
      continue;
    }

    if (currentMap == null) {
      continue;
    }

    final libraryMatch = RegExp(r"^'([^']+)':\s*\[$").firstMatch(line);
    if (libraryMatch != null) {
      currentLibrary = libraryMatch.group(1)!;
      symbolMaps[currentMap]![currentLibrary] = <String>[];
      continue;
    }

    final symbolMatch = RegExp(r"^'([^']+)'[,]?$").firstMatch(line);
    if (symbolMatch != null && currentLibrary != null) {
      symbolMaps[currentMap]![currentLibrary]!.add(symbolMatch.group(1)!);
      continue;
    }

    if (line == '],') {
      currentLibrary = null;
      continue;
    }

    if (line == '};') {
      currentMap = null;
      currentLibrary = null;
    }
  }

  return symbolMaps;
}

Map<String, String> _parseGetterMap(String content) {
  final getterMap = <String, String>{};
  final pattern = RegExp(
    r'Tizen\w+Native\?\s+_(\w+);\s+Tizen\w+Native get (\w+)\s*=>.*?_getTizenNative\((\w+)\);',
    multiLine: true,
    dotAll: true,
  );

  for (final match in pattern.allMatches(content)) {
    getterMap[match.group(3)!] = match.group(2)!;
  }
  return getterMap;
}

Map<String, String> _parseSymgenDescriptions(List<String> lines) {
  final descriptions = <String, String>{};
  final pattern = RegExp(r'-\s+([\w\.\-]+)\s+.*#\s+(.*)$');

  for (final line in lines) {
    final match = pattern.firstMatch(line);
    if (match != null) {
      descriptions[match.group(1)!.trim()] = match.group(2)!.trim();
    }
  }

  return descriptions;
}

CallbackInteropInfo _parseCallbackInteropInfo(String content) {
  final helperClassName =
      RegExp(r'class\s+(\w+)\s*\{').firstMatch(content)?.group(1) ??
          'TizenInteropCallbacks';
  final registeredCallbackTypeName =
      RegExp(r'class\s+(\w+)<NativeCbType extends Function>\s*\{')
              .firstMatch(content)
              ?.group(1) ??
          'RegisteredCallback';
  final registrationMethodName = RegExp(
        r'(\w+)<NativeCbType extends Function>\(\s*String callbackName,',
        dotAll: true,
      ).firstMatch(content)?.group(1) ??
      'register';
  final pointerGetterName =
      RegExp(r'Pointer<NativeFunction<NativeCbType>> get (\w+) =>')
              .firstMatch(content)
              ?.group(1) ??
          'interopCallback';
  final userDataGetterName =
      RegExp(r'Pointer<Void> get (\w+) =>').firstMatch(content)?.group(1) ??
          'interopUserData';

  return CallbackInteropInfo(
    helperClassName: helperClassName,
    registrationMethodName: registrationMethodName,
    registeredCallbackTypeName: registeredCallbackTypeName,
    pointerGetterName: pointerGetterName,
    userDataGetterName: userDataGetterName,
  );
}

Iterable<String> _extractReferencedCallbackTypes(
  MethodInfo method,
  Map<String, CallbackTypedefGroup> callbackGroups,
) sync* {
  final seen = <String>{};
  for (final parameter in method.parameters) {
    final callbackType = parameter.type.trim();
    if (!callbackGroups.containsKey(callbackType) || !seen.add(callbackType)) {
      continue;
    }
    yield callbackType;
  }
}

bool _looksLikeCallbackApiSymbol(String symbol) {
  return symbol.endsWith('_cb') ||
      symbol.contains('_cb_') ||
      symbol.contains('_callback') ||
      symbol.contains('callback');
}

String _buildModuleLibrary({
  required String version,
  required String categoryName,
  required ModuleInfo module,
  required CallbackInteropInfo callbackInterop,
}) {
  final buffer = StringBuffer()
    ..writeln(_generatedMarker)
    ..writeln(
      '// ignore_for_file: camel_case_types, non_constant_identifier_names, '
      'unused_import',
    )
    ..writeln()
    ..writeln(
      '/// Module-scoped documentation wrappers for `${module.getterName}`.',
    )
    ..writeln('///')
    ..writeln(
        '/// Pub.dev import path: `package:tizen_interop/$version/tizen/${module.fileName}`.')
    ..writeln('/// Tizen version: `$version`.')
    ..writeln('/// Module getter: `${module.getterName}`.')
    ..writeln('/// Module symbol map: `${module.symbolMapVariable}`.')
    ..writeln(
      '/// Shared object(s): '
      '${module.sharedObjects.map((value) => '`$value`').join(', ')}.',
    )
    ..writeln('///')
    ..writeln('/// ${module.descriptionText}.')
    ..writeln('///')
    ..writeln(
      '/// Generated from `generated_symbols.dart` and '
      '`generated_bindings.dart` in `package:tizen_interop`.',
    );

  if (module.callbackRelatedMissingSymbols.isNotEmpty) {
    buffer
      ..writeln('///')
      ..writeln(
        '/// Callback-related symbols declared in `generated_symbols.dart` '
        'but not found in `generated_bindings.dart`:',
      );
    for (final symbol in module.callbackRelatedMissingSymbols) {
      buffer.writeln('/// - `$symbol`');
    }
    buffer
      ..writeln('///')
      ..writeln(
        '/// For callback interop, inspect '
        '`package:tizen_interop_callbacks/tizen_interop_callbacks.dart` and use '
        '`${callbackInterop.helperClassName}.'
        '${callbackInterop.registrationMethodName}<NativeCbType>()`, then pass '
        '`${callbackInterop.registeredCallbackTypeName}.'
        '${callbackInterop.pointerGetterName}` and '
        '`${callbackInterop.registeredCallbackTypeName}.'
        '${callbackInterop.userDataGetterName}` to the native API.',
      );
  }

  if (module.unresolvedSymbols.isNotEmpty) {
    buffer
      ..writeln('///')
      ..writeln(
        '/// Symbols declared in `generated_symbols.dart` but not found in '
        '`generated_bindings.dart`:',
      );
    for (final symbol in module.unresolvedSymbols) {
      buffer.writeln('/// - `$symbol`');
    }
  }

  buffer
    ..writeln('///')
    ..writeln('/// {@category $categoryName}')
    ..writeln('library ${module.libraryName};')
    ..writeln()
    ..writeln("import 'dart:ffi' as ffi;")
    ..writeln()
    ..writeln("import 'package:tizen_interop/$version/tizen.dart';")
    ..writeln(
      "import 'package:tizen_interop/src/bindings/$version/"
      "generated_bindings.dart' as bindings;",
    );

  if (module.callbackReferences.isNotEmpty) {
    buffer.writeln();
    for (var index = 0; index < module.callbackReferences.length; index++) {
      if (index > 0) {
        buffer.writeln();
      }
      _writeCallbackAliasBlock(
        buffer: buffer,
        callbackReference: module.callbackReferences[index],
        callbackInterop: callbackInterop,
      );
    }
  }

  if (module.methods.isNotEmpty) {
    buffer.writeln();
    for (var index = 0; index < module.methods.length; index++) {
      if (index > 0) {
        buffer.writeln();
      }
      _writeMethodWrapper(buffer, module, module.methods[index]);
    }
  }

  return buffer.toString();
}

void _writeCallbackAliasBlock({
  required StringBuffer buffer,
  required CallbackReference callbackReference,
  required CallbackInteropInfo callbackInterop,
}) {
  final group = callbackReference.group;

  for (final docLine in group.docLines) {
    buffer.writeln(_normalizeDocLine(docLine));
  }

  if (group.docLines.isNotEmpty) {
    buffer.writeln('///');
  }

  final usedByMethods = callbackReference.usedByMethods
      .map((methodName) => '[$methodName]')
      .join(', ');

  buffer
    ..writeln(
      '/// Register this callback with `'
      '${callbackInterop.helperClassName}.'
      '${callbackInterop.registrationMethodName}<${group.nativeSignatureType}>()` '
      'from `package:tizen_interop_callbacks`.',
    )
    ..writeln(
      '/// Pass `'
      '${callbackInterop.registeredCallbackTypeName}.'
      '${callbackInterop.pointerGetterName}` and `'
      '${callbackInterop.registeredCallbackTypeName}.'
      '${callbackInterop.userDataGetterName}` to the native API.',
    );

  if (usedByMethods.isNotEmpty) {
    buffer.writeln('/// Used by: $usedByMethods.');
  }

  buffer
    ..writeln('typedef ${group.callbackType} = bindings.${group.callbackType};')
    ..writeln()
    ..writeln(
      '/// Native callback signature used with '
      '`'
      '${callbackInterop.helperClassName}.'
      '${callbackInterop.registrationMethodName}<${group.nativeSignatureType}>()`.',
    )
    ..writeln(
      'typedef ${group.nativeSignatureType} = '
      'bindings.${group.nativeSignatureType};',
    );

  final dartSignatureType = group.dartSignatureType;
  if (dartSignatureType != null) {
    buffer
      ..writeln()
      ..writeln(
        '/// Dart-side callback signature paired with '
        '[${group.nativeSignatureType}].',
      )
      ..writeln(
        'typedef $dartSignatureType = bindings.$dartSignatureType;',
      );
  }
}

void _writeMethodWrapper(
  StringBuffer buffer,
  ModuleInfo module,
  MethodInfo method,
) {
  for (final docLine in method.docLines) {
    buffer.writeln(_normalizeDocLine(docLine));
  }

  if (method.docLines.isNotEmpty) {
    buffer
      ..writeln('///')
      ..writeln('/// Module getter: `${module.getterName}`.');
  }

  if (method.parameters.isEmpty) {
    buffer
      ..writeln('${method.returnType} ${method.name}() =>')
      ..writeln('    ${module.getterName}.${method.name}();');
    return;
  }

  buffer..writeln('${method.returnType} ${method.name}(');
  for (final parameter in method.parameters) {
    buffer.writeln('  ${parameter.type} ${parameter.name},');
  }
  buffer
    ..writeln(') =>')
    ..writeln('    ${module.getterName}.${method.name}(');
  for (final parameter in method.parameters) {
    buffer.writeln('      ${parameter.name},');
  }
  buffer..writeln('    );');
}

String _buildLandingLibrary({
  required String version,
  required String categoryName,
  required List<ModuleInfo> modules,
}) {
  final versionId = version.replaceAll('.', '_');
  final moduleBullets = modules
      .map(
        (module) => '/// - `${module.moduleSlug}`: '
            '`package:tizen_interop/$version/tizen/${module.fileName}`',
      )
      .join('\n');

  return '''
$_generatedMarker

/// Landing library for Tizen $version module-scoped pub.dev docs.
///
/// Pub.dev import path: `package:tizen_interop/$version/tizen/index.dart`.
///
/// Use this page to choose a single module library instead of browsing the
/// monolithic `package:tizen_interop/$version/tizen.dart` API page.
///
/// Modules:
$moduleBullets
///
/// {@category $categoryName}
library tizen_${versionId}_tizen;
''';
}

String _buildCategoryMarkdown({
  required String version,
  required List<ModuleInfo> modules,
}) {
  final moduleList = modules
      .map(
        (module) =>
            '- `${module.moduleSlug}`: `package:tizen_interop/$version/tizen/${module.fileName}`',
      )
      .join('\n');

  return '''
# Tizen $version / tizen

These pages are generated at publish time so pub.dev does not render one
oversized API page for `package:tizen_interop/$version/tizen.dart`.

## Recommended navigation

1. Open `package:tizen_interop/$version/tizen/index.dart`.
2. Pick one module library.
3. Read only that module's API list.

## Recommended imports

- `package:tizen_interop/$version/tizen/index.dart`
- `package:tizen_interop/$version/tizen/<module>.dart`

## Modules

$moduleList
''';
}

String _buildFooterText({
  required String version,
  required List<ModuleInfo> modules,
}) {
  return 'Generated module-scoped pub.dev docs for Tizen $version. '
      'Landing library: package:tizen_interop/$version/tizen/index.dart. '
      'Module libraries: ${modules.length}.';
}

String _buildDartdocOptions({
  required String version,
  required String versionId,
  required String categoryName,
  required List<ModuleInfo> modules,
  required String footerTextPath,
}) {
  final includes = [
    'tizen_${versionId}_tizen',
    ...modules.map((module) => module.libraryName),
  ].map((library) => '    - $library').join('\n');

  return '''
$_yamlGeneratedMarker
# Publish-time dartdoc configuration for Tizen $version.
# This file is temporary and is created by scripts/prepare_pubdev_module_docs.sh.
# pub.dev builds API docs only from the uploaded package contents, so the
# generated wrapper libraries and this file must exist before publishing.
dartdoc:
  # Group the generated wrapper libraries under one topic page.
  categories:
    $categoryName:
      markdown: doc/dartdoc/tizen_$versionId.md
      displayName: Tizen $version / tizen
  categoryOrder:
    - $categoryName

  # Hide the original monolithic library from the published API docs.
  exclude:
    - tizen_interop

  # Explain that these are generated module-scoped wrapper pages.
  footerText:
    - $footerTextPath

  # Publish only the generated landing library and the module wrapper libraries.
  include:
$includes
''';
}

String _camelToSnake(String value) {
  return value
      .replaceAllMapped(
        RegExp(r'([a-z0-9])([A-Z])'),
        (match) => '${match.group(1)}_${match.group(2)}',
      )
      .toLowerCase();
}

String _moduleSlugFromGetter(String getterName) {
  const prefix = 'tizen';
  final trimmed = getterName.startsWith(prefix)
      ? getterName.substring(prefix.length)
      : getterName;
  return _camelToSnake(trimmed).replaceFirst(RegExp(r'^_+'), '');
}

String _normalizeDocLine(String line) {
  return line
      .replaceAll('@param[in,out]', 'Parameter')
      .replaceAll('@param[out]', 'Output parameter')
      .replaceAll('@param[in]', 'Parameter')
      .replaceAll('[in,out]', 'in,out')
      .replaceAll('[out]', 'out')
      .replaceAll('[in]', 'in');
}

Future<void> _run(
  String executable,
  List<String> arguments, {
  required String workingDirectory,
}) async {
  final process = await Process.start(
    executable,
    arguments,
    workingDirectory: workingDirectory,
  );
  final stdoutDone = stdout.addStream(process.stdout);
  final stderrDone = stderr.addStream(process.stderr);
  final exitCode = await process.exitCode;
  await stdoutDone;
  await stderrDone;

  if (exitCode != 0) {
    throw ProcessException(executable, arguments, '', exitCode);
  }
}

Future<void> _runPublishDryRun({
  required String workingDirectory,
}) async {
  final result = await Process.run(
    'dart',
    ['pub', 'publish', '--dry-run'],
    workingDirectory: workingDirectory,
  );

  stdout.write(result.stdout);
  stderr.write(result.stderr);

  if (result.exitCode == 0) {
    return;
  }

  final output = '${result.stdout}\n${result.stderr}';
  final hasOnlyWarnings = RegExp(r'Package has \d+ warning').hasMatch(output) &&
      !RegExp(r'Package has .*error', caseSensitive: false).hasMatch(output);
  if (hasOnlyWarnings) {
    stdout.writeln(
      'dart pub publish --dry-run returned warnings only; continuing.',
    );
    return;
  }

  throw ProcessException(
    'dart',
    const ['pub', 'publish', '--dry-run'],
    '',
    result.exitCode,
  );
}
