import 'dart:convert';
import 'dart:io';

const _generatedMarker =
    '// Generated by tool/prepare_pubdev_module_docs.dart. Do not edit.';
const _yamlGeneratedMarker =
    '# Generated by tool/prepare_pubdev_module_docs.dart. Do not edit.';

class _Config {
  _Config({
    required this.command,
    required this.version,
    required this.keepGenerated,
  });

  final String command;
  final String version;
  final bool keepGenerated;
}

class _GeneratedModule {
  _GeneratedModule({
    required this.libraryName,
    required this.fileName,
    required this.moduleSlug,
    required this.getterName,
  });

  final String libraryName;
  final String fileName;
  final String moduleSlug;
  final String getterName;
}

class _State {
  _State({
    required this.version,
    required this.generatedFiles,
    required this.directoriesToPrune,
    required this.dartdocOptionsBackupPath,
  });

  final String version;
  final List<String> generatedFiles;
  final List<String> directoriesToPrune;
  final String? dartdocOptionsBackupPath;

  Map<String, Object?> toJson() => {
        'version': version,
        'generatedFiles': generatedFiles,
        'directoriesToPrune': directoriesToPrune,
        'dartdocOptionsBackupPath': dartdocOptionsBackupPath,
      };

  static _State fromJson(Map<String, Object?> json) {
    return _State(
      version: json['version']! as String,
      generatedFiles: (json['generatedFiles']! as List<Object?>).cast<String>(),
      directoriesToPrune:
          (json['directoriesToPrune']! as List<Object?>).cast<String>(),
      dartdocOptionsBackupPath: json['dartdocOptionsBackupPath'] as String?,
    );
  }
}

Future<void> main(List<String> args) async {
  final config = _parseArgs(args);
  final rootDir = _repoRoot();

  switch (config.command) {
    case 'prepare':
      await _prepare(rootDir, config);
      return;
    case 'verify':
      await _prepare(rootDir, config);
      final versionId = config.version.replaceAll('.', '_');
      try {
        await _run(
          'dart',
          [
            'doc',
            '--validate-links',
            '-o',
            '.dart_tool/pubdev_module_docs/$versionId/preview',
            '.',
          ],
          workingDirectory: rootDir.path,
        );
        await _runPublishDryRun(
          workingDirectory: rootDir.path,
        );
      } finally {
        if (!config.keepGenerated) {
          _clean(rootDir, config.version);
        }
      }
      return;
    case 'clean':
      _clean(rootDir, config.version);
      return;
    default:
      throw ArgumentError('Unknown command: ${config.command}');
  }
}

_Config _parseArgs(List<String> args) {
  var command = 'verify';
  var version = '6.0';
  var keepGenerated = false;

  for (var index = 0; index < args.length; index++) {
    final arg = args[index];
    switch (arg) {
      case 'prepare':
      case 'verify':
      case 'clean':
        command = arg;
      case '--version':
        if (index + 1 >= args.length) {
          throw ArgumentError('Missing value for --version');
        }
        version = args[++index];
      case '--keep-generated':
        keepGenerated = true;
      case '-h':
      case '--help':
        stdout.writeln(
          'Usage: dart run tool/prepare_pubdev_module_docs.dart '
          '[prepare|verify|clean] [--version 6.0] [--keep-generated]',
        );
        exit(0);
      default:
        throw ArgumentError('Unknown argument: $arg');
    }
  }

  return _Config(
    command: command,
    version: version,
    keepGenerated: keepGenerated,
  );
}

Directory _repoRoot() {
  final scriptFile = File.fromUri(Platform.script);
  return scriptFile.parent.parent;
}

Future<void> _prepare(Directory rootDir, _Config config) async {
  _clean(rootDir, config.version, allowMissing: true);

  final versionId = config.version.replaceAll('.', '_');
  final stateDir =
      Directory('${rootDir.path}/.dart_tool/pubdev_module_docs/$versionId')
        ..createSync(recursive: true);
  final tempDartdocBackupFile = File(
    '${rootDir.path}/dartdoc_options.yaml.module_doc_backup',
  );
  final stateBackupFile = File('${stateDir.path}/dartdoc_options.yaml.backup');
  if (stateBackupFile.existsSync()) {
    stateBackupFile.deleteSync();
  }

  await _run(
    'dart',
    [
      'run',
      'tool/generate_module_dartdoc.dart',
      '--version',
      config.version,
      '--no-build-docs',
      '--keep-temp-files',
      '--keep-dartdoc-options',
    ],
    workingDirectory: rootDir.path,
  );

  if (tempDartdocBackupFile.existsSync()) {
    tempDartdocBackupFile.renameSync(stateBackupFile.path);
  }

  final tempLibDir = Directory(
    '${rootDir.path}/lib/module_docs/$versionId/modules',
  );
  if (!tempLibDir.existsSync()) {
    throw StateError(
        'Temporary module docs were not generated: ${tempLibDir.path}');
  }

  final targetDir = Directory('${rootDir.path}/lib/${config.version}/tizen');
  if (targetDir.existsSync()) {
    final existingFiles = targetDir
        .listSync(recursive: true)
        .whereType<File>()
        .map((file) => file.path)
        .toList(growable: false);
    if (existingFiles.isNotEmpty) {
      throw StateError(
        'Refusing to overwrite existing files in ${targetDir.path}. '
        'Run clean first or inspect the directory.',
      );
    }
  }
  targetDir.createSync(recursive: true);

  final categoryName = 'tizen_$versionId';
  final moduleFiles = tempLibDir
      .listSync()
      .whereType<File>()
      .where((file) => file.path.endsWith('.dart'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  final generatedModules = <_GeneratedModule>[];
  final generatedFiles = <String>[];

  for (final file in moduleFiles) {
    final content = file.readAsStringSync();
    final libraryName = _extractLibraryName(content);
    final getterName = _extractGetterName(content);
    final tempFileName = _basename(file.path);
    final moduleSlug = _publicModuleSlug(tempFileName);
    final fileName = '$moduleSlug.dart';
    final rewrittenContent = _rewriteModuleLibrary(
      content: content,
      version: config.version,
      fileName: fileName,
      categoryName: categoryName,
    );
    final outputFile = File('${targetDir.path}/$fileName')
      ..writeAsStringSync(rewrittenContent);
    generatedFiles.add(outputFile.path);
    generatedModules.add(
      _GeneratedModule(
        libraryName: libraryName,
        fileName: fileName,
        moduleSlug: moduleSlug,
        getterName: getterName,
      ),
    );
  }

  final landingFile = File('${targetDir.path}/index.dart')
    ..writeAsStringSync(
      _buildLandingLibrary(
        version: config.version,
        categoryName: categoryName,
        generatedModules: generatedModules,
      ),
    );
  generatedFiles.add(landingFile.path);

  final categoryDocFile = File(
    '${rootDir.path}/doc/dartdoc/tizen_$versionId.md',
  );
  categoryDocFile.parent.createSync(recursive: true);
  categoryDocFile.writeAsStringSync(
    _buildCategoryMarkdown(
      version: config.version,
      categoryName: categoryName,
      landingLibraryName: 'tizen_${versionId}_tizen',
      generatedModules: generatedModules,
    ),
  );
  generatedFiles.add(categoryDocFile.path);

  final dartdocOptionsFile = File('${rootDir.path}/dartdoc_options.yaml')
    ..writeAsStringSync(
      _buildDartdocOptions(
        categoryName: categoryName,
        versionId: versionId,
        generatedModules: generatedModules,
      ),
    );
  generatedFiles.add(dartdocOptionsFile.path);

  final moduleDocsDir = Directory('${rootDir.path}/lib/module_docs');
  if (moduleDocsDir.existsSync()) {
    moduleDocsDir.deleteSync(recursive: true);
  }

  final state = _State(
    version: config.version,
    generatedFiles: generatedFiles,
    directoriesToPrune: [
      targetDir.path,
      categoryDocFile.parent.path,
      stateDir.path,
    ],
    dartdocOptionsBackupPath:
        stateBackupFile.existsSync() ? stateBackupFile.path : null,
  );
  _stateFile(rootDir, config.version)
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(
      const JsonEncoder.withIndent('  ').convert(state.toJson()),
    );

  stdout.writeln(
    'Prepared ${generatedModules.length} module libraries for pub.dev under '
    '${targetDir.path}',
  );
}

void _clean(
  Directory rootDir,
  String version, {
  bool allowMissing = false,
}) {
  final stateFile = _stateFile(rootDir, version);
  if (!stateFile.existsSync()) {
    if (!allowMissing) {
      stdout.writeln(
          'No generated pub.dev module docs state found for $version.');
    }
    final staleTempDir = Directory(
        '${rootDir.path}/lib/module_docs/${version.replaceAll('.', '_')}');
    if (staleTempDir.existsSync()) {
      staleTempDir.deleteSync(recursive: true);
    }
    return;
  }

  final state = _State.fromJson(
    jsonDecode(stateFile.readAsStringSync()) as Map<String, Object?>,
  );

  for (final path in state.generatedFiles.reversed) {
    final file = File(path);
    if (file.existsSync()) {
      file.deleteSync();
    }
  }

  final dartdocOptionsFile = File('${rootDir.path}/dartdoc_options.yaml');
  if (dartdocOptionsFile.existsSync()) {
    final content = dartdocOptionsFile.readAsStringSync();
    if (content.startsWith(_yamlGeneratedMarker)) {
      dartdocOptionsFile.deleteSync();
    }
  }

  final backupPath = state.dartdocOptionsBackupPath;
  if (backupPath != null) {
    final backupFile = File(backupPath);
    if (backupFile.existsSync()) {
      if (dartdocOptionsFile.existsSync()) {
        dartdocOptionsFile.deleteSync();
      }
      backupFile.renameSync(dartdocOptionsFile.path);
    }
  }

  for (final directoryPath in state.directoriesToPrune.reversed) {
    _deleteEmptyDirectoryChain(directoryPath, stopAt: rootDir.path);
  }

  final moduleDocsDir = Directory('${rootDir.path}/lib/module_docs');
  if (moduleDocsDir.existsSync()) {
    moduleDocsDir.deleteSync(recursive: true);
  }

  if (stateFile.existsSync()) {
    stateFile.deleteSync();
  }
}

File _stateFile(Directory rootDir, String version) {
  final versionId = version.replaceAll('.', '_');
  return File(
    '${rootDir.path}/.dart_tool/pubdev_module_docs/$versionId/state.json',
  );
}

void _deleteEmptyDirectoryChain(
  String directoryPath, {
  required String stopAt,
}) {
  var current = Directory(directoryPath);
  final stopPath = Directory(stopAt).absolute.path;
  while (current.existsSync() && current.absolute.path.startsWith(stopPath)) {
    if (current.absolute.path == stopPath) {
      return;
    }
    if (current.listSync().isNotEmpty) {
      return;
    }
    final parent = current.parent;
    current.deleteSync();
    current = parent;
  }
}

String _extractLibraryName(String content) {
  final match = RegExp(r'^library\s+([A-Za-z0-9_]+);$', multiLine: true)
      .firstMatch(content);
  if (match == null) {
    throw StateError('Unable to find library name.');
  }
  return match.group(1)!;
}

String _extractGetterName(String content) {
  final match = RegExp(
    r'^/// Module getter: `([^`]+)`\.$',
    multiLine: true,
  ).firstMatch(content);
  if (match == null) {
    throw StateError('Unable to find module getter name.');
  }
  return match.group(1)!;
}

String _rewriteModuleLibrary({
  required String content,
  required String version,
  required String fileName,
  required String categoryName,
}) {
  final libraryMatch = RegExp(r'^library\s+[A-Za-z0-9_]+;$', multiLine: true)
      .firstMatch(content);
  if (libraryMatch == null) {
    throw StateError('Unable to find library directive in $fileName.');
  }

  final insertion = '''
///
/// Pub.dev import path: `package:tizen_interop/$version/tizen/$fileName`.
///
/// {@category $categoryName}
''';

  return '$_generatedMarker\n'
      '${content.replaceFirst(libraryMatch.group(0)!, '$insertion${libraryMatch.group(0)!}')}';
}

String _buildLandingLibrary({
  required String version,
  required String categoryName,
  required List<_GeneratedModule> generatedModules,
}) {
  final versionId = version.replaceAll('.', '_');
  final moduleLinks = generatedModules
      .map(
        (module) =>
            '/// <li><a href="../${module.libraryName}/">${module.moduleSlug}</a> '
            '<code>${module.getterName}</code></li>',
      )
      .join('\n');

  return '''
$_generatedMarker
// ignore_for_file: unintended_html_in_doc_comment

/// Landing library for Tizen $version module-scoped pub.dev docs.
///
/// Pub.dev import path: `package:tizen_interop/$version/tizen/index.dart`.
///
/// This page exists so pub.dev exposes a small `tizen` entry point instead of
/// forcing readers into the monolithic `package:tizen_interop/$version/tizen.dart`
/// library page.
///
/// <ul>
$moduleLinks
/// </ul>
///
/// {@category $categoryName}
library tizen_${versionId}_tizen;
''';
}

String _buildCategoryMarkdown({
  required String version,
  required String categoryName,
  required String landingLibraryName,
  required List<_GeneratedModule> generatedModules,
}) {
  final modules = generatedModules
      .map(
        (module) =>
            '- `${module.moduleSlug}`: `package:tizen_interop/$version/tizen/${module.fileName}`',
      )
      .join('\n');

  return '''
# Tizen $version / tizen

This category is generated for pub.dev documentation.

- Category tag: `$categoryName`
- Landing library: `$landingLibraryName`
- Goal: expose module-scoped API pages instead of the single large
  `package:tizen_interop/$version/tizen.dart` library page.

## Modules

$modules
''';
}

String _buildDartdocOptions({
  required String categoryName,
  required String versionId,
  required List<_GeneratedModule> generatedModules,
}) {
  final includes = [
    'tizen_${versionId}_tizen',
    ...generatedModules.map((module) => module.libraryName),
  ].map((library) => '    - $library').join('\n');

  return '''
$_yamlGeneratedMarker
dartdoc:
  categories:
    $categoryName:
      markdown: doc/dartdoc/tizen_$versionId.md
      displayName: Tizen ${versionId.replaceAll('_', '.')} / tizen
  categoryOrder:
    - $categoryName
  include:
$includes
''';
}

String _basename(String path) {
  final normalized = path.replaceAll('\\', '/');
  return normalized.substring(normalized.lastIndexOf('/') + 1);
}

String _publicModuleSlug(String tempFileName) {
  final withoutExtension =
      tempFileName.substring(0, tempFileName.length - '.dart'.length);
  return withoutExtension.startsWith('tizen_')
      ? withoutExtension.substring('tizen_'.length)
      : withoutExtension;
}

Future<void> _run(
  String executable,
  List<String> arguments, {
  required String workingDirectory,
}) async {
  final process = await Process.start(
    executable,
    arguments,
    workingDirectory: workingDirectory,
  );
  final stdoutDone = stdout.addStream(process.stdout);
  final stderrDone = stderr.addStream(process.stderr);
  final exitCode = await process.exitCode;
  await stdoutDone;
  await stderrDone;
  if (exitCode != 0) {
    throw ProcessException(executable, arguments, '', exitCode);
  }
}

Future<void> _runPublishDryRun({
  required String workingDirectory,
}) async {
  final result = await Process.run(
    'dart',
    ['pub', 'publish', '--dry-run'],
    workingDirectory: workingDirectory,
  );

  stdout.write(result.stdout);
  stderr.write(result.stderr);

  if (result.exitCode == 0) {
    return;
  }

  final output = '${result.stdout}\n${result.stderr}';
  final hasOnlyWarnings = RegExp(r'Package has \d+ warning').hasMatch(output) &&
      !RegExp(r'Package has .*error', caseSensitive: false).hasMatch(output);
  if (hasOnlyWarnings) {
    stdout.writeln(
      'dart pub publish --dry-run returned warnings only; continuing.',
    );
    return;
  }

  throw ProcessException(
    'dart',
    const ['pub', 'publish', '--dry-run'],
    '',
    result.exitCode,
  );
}
